// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB68hMKG0JrA4ZT7G7BOGgligy48L3a2rk',
    appId: '1:1047082930833:web:b0ae91344644bc13866530',
    messagingSenderId: '1047082930833',
    projectId: 'vaccitrack-7d5a4',
    authDomain: 'vaccitrack-7d5a4.firebaseapp.com',
    storageBucket: 'vaccitrack-7d5a4.firebasestorage.app',
    measurementId: 'G-441JT4NV10',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAaN7hJdpU0tjQ0xnHISZMM0nRd7h3O1io',
    appId: '1:1047082930833:android:6c6d90679d6195a4866530',
    messagingSenderId: '1047082930833',
    projectId: 'vaccitrack-7d5a4',
    storageBucket: 'vaccitrack-7d5a4.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB68hMKG0JrA4ZT7G7BOGgligy48L3a2rk',
    appId: '1:1047082930833:web:ec7637527bd3e8f9866530',
    messagingSenderId: '1047082930833',
    projectId: 'vaccitrack-7d5a4',
    authDomain: 'vaccitrack-7d5a4.firebaseapp.com',
    storageBucket: 'vaccitrack-7d5a4.firebasestorage.app',
    measurementId: 'G-0MTJGNG04B',
  );
}
